projectName: SABER
version: 3.1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run-script build
        - npm run-script start
  artifacts:
    baseDirectory: src
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

