version: 3.1
frontend:
  buildpath:
  phases:
    build:
      commands:
        - npm run-script build
        - npm run-script start
  artifacts:
    files:
        - "**/*"
    discard-paths: yes
    baseDirectory: "src"